const municipiosPorEstado : Record<string, string[]> = {
    AG: [
        "Aguascalientes", "Jesús María", "San Francisco de los Romo", "Calvillo", "Rincón de Romos", "Asientos", "Pabellón de Arteaga", "Tepezalá", "El Llano", "Cosío", "San José de Gracia"
    ],
    BC: [
        'Ensenada', 'Mexicali', 'Playas de Rosarito', 'Tecate', 'Tijuana', 'San Quintín', 'San Felipe'
    ],
    BS: [
        'Comondú', 'La Paz', 'Loreto', 'Los Cabos', 'Mulegé'
    ],
    CM: [
        'Calakmul', 'Calkiní', 'Campeche', 'Candelaria', 'Carmen', 'Champotón', 'Escárcega', 'Hecelchakán', 'Hopelchén', 'Palizada', 'Tenabo', 'Dzitbalché', 'Seybaplaya'
    ],
    CS: [
        "Acacoyagua","Acala","Acapetahua","Altamirano","Amatán","Amatenango de la Frontera","Amatenango del Valle","Ángel Albino Corzo","Arriaga","Bejucal de Ocampo","Bella Vista","Berriozábal","Bochil","El Bosque","Cacahoatán","Catazajá","Cintalapa","Coapilla","Comitán de Domínguez","La Concordia","Copainalá","Chalchihuitán","Chamula","Chanal","Chapultenango","Chenalhó","Chiapa de Corzo","Chiapilla","Chicoasén","Chicomuselo","Chilón","Escuintla","Francisco León","Frontera Comalapa","Frontera Hidalgo","La Grandeza","Huehuetán","Huixtán","Huitiupán","Huixtla","La Independencia","Ixhuatán","Ixtacomitán","Ixtapa","Ixtapangajoya","Jiquipilas","Jitotol","Juárez","Larráinzar","La Libertad","Mapastepec","Las Margaritas","Mazapa de Madero","Mazatán","Metapa","Mitontic","Motozintla","Nicolás Ruiz","Ocosingo","Ocotepec","Ocozocoautla de Espinosa","Ostuacán","Osumacinta","Oxchuc","Palenque","Pantelhó","Pantepec","Pichucalco","Pijijiapan","El Porvenir","Villa Comaltitlán","Pueblo Nuevo Solistahuacán","Rayón","Reforma","Las Rosas","Sabanilla","Salto de Agua","San Cristóbal de Las Casas","San Fernando","Siltepec","Simojovel","Sitalá","Socoltenango","Solosuchiapa","Soyaló","Suchiapa","Suchiate","Sunuapa","Tapachula","Tapalapa","Tapilula","Tecpatán","Tenejapa","Teopisca", "Tila",
    ],
    CH: [
        "Ahumada", "Aldama", "Allende", "Aquiles Serdán", "Ascensión", "Bachíniva", "Balleza", "Batopilas de Manuel Gómez Morín", "Bocoyna", "Buenaventura", "Camargo", "Carichí", "Casas Grandes", "Coronado", "Coyame del Sotol", "La Cruz", "Cuauhtémoc", "Cusihuiriachi", "Chihuahua", "Chínipas", "Delicias", "Dr. Belisario Domínguez", "Galeana", "Santa Isabel", "Gómez Farías", "Gran Morelos", "Guachochi", "Guadalupe", "Guadalupe y Calvo", "Guazapares", "Guerrero", "Hidalgo del Parral", "Huejotitán", "Ignacio Zaragoza", "Janos", "Jiménez", "Juárez", "Julimes", "López", "Madera", "Maguarichi", "Manuel Benavides", "Matachí", "Matamoros", "Meoqui", "Morelos", "Moris", "Namiquipa", "Nonoava", "Nuevo Casas Grandes", "Ocampo", "Ojinaga", "Práxedis G. Guerrero", "Riva Palacio", "Rosales", "Rosario", "San Francisco de Borja", "San Francisco de Conchos", "San Francisco del Oro", "Santa Bárbara", "Satevó", "Saucillo", "Temósachic", "El Tule", "Urique", "Uruachi", "Valle de Zaragoza"
    ],
    CX: [
        "Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán", "Cuajimalpa de Morelos", "Cuauhtémoc", "Gustavo A. Madero", "Iztacalco", "Iztapalapa", "La Magdalena Contreras", "Miguel Hidalgo", "Milpa Alta", "Tláhuac", "Tlalpan", "Venustiano Carranza", "Xochimilco"
    ],
    CO: [
        "Abasolo", "Acuña", "Allende", "Arteaga", "Candela", "Castaños", "Cuatro Ciénegas", "Escobedo", "Francisco I. Madero", "Frontera", "General Cepeda", "Guerrero", "Hidalgo", "Jiménez", "Juárez", "Lamadrid", "Matamoros", "Monclova", "Morelos", "Múzquiz", "Nadadores", "Nava", "Ocampo", "Parras", "Piedras Negras", "Progreso", "Ramos Arizpe", "Sabinas", "Sacramento", "Saltillo", "San Buenaventura", "San Juan de Sabinas", "San Pedro", "Sierra Mojada", "Torreón", "Viesca", "Villa Unión", "Zaragoza"
    ],
    CL: [
        "Armería", "Colima", "Comala", "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", "Manzanillo", "Minatitlán", "Tecomán", "Villa de Álvarez"
    ],
    DG: [
        "Canatlán", "Canelas", "Coneto de Comonfort", "Cuencamé", "Durango", "General Simón Bolívar", "Gómez Palacio", "Guadalupe Victoria", "Guanaceví", "Hidalgo", "Indé", "Lerdo", "Mapimí", "Mezquital", "Nazas", "Nombre de Dios", "Ocampo", "El Oro", "Otáez", "Pánuco de Coronado", "Peñón Blanco", "Poanas", "Pueblo Nuevo", "Rodeo", "San Bernardo", "San Dimas", "San Juan de Guadalupe", "San Juan del Río", "San Luis del Cordero", "San Pedro del Gallo", "Santa Clara", "Santiago Papasquiaro", "Súchil", "Tamazula", "Tepehuanes", "Tlahualilo", "Topia", "Vicente Guerrero", "Nuevo Ideal"
    ],
    GT: [
        "Abasolo", "Acámbaro", "San Miguel de Allende", "Apaseo el Alto", "Apaseo el Grande", "Atarjea", "Celaya", "Manuel Doblado", "Comonfort", "Coroneo", "Cortazar", "Cuerámaro", "Doctor Mora", "Dolores Hidalgo", "Guanajuato", "Huanímaro", "Irapuato", "Jaral del Progreso", "Jerécuaro", "León", "Moroleón", "Ocampo", "Pénjamo", "Pueblo Nuevo", "Purísima del Rincón", "Romita", "Salamanca", "Salvatierra", "San Diego de la Unión", "San Felipe", "San Francisco del Rincón", "San José Iturbide", "San Luis de la Paz", "Santa Catarina", "Santa Cruz de Juventino Rosas", "Santiago Maravatío", "Silao de la Victoria", "Tarandacuao", "Tarimoro", "Tierra Blanca", "Uriangato", "Valle de Santiago", "Victoria", "Villagrán", "Xichú", "Yuriria"
    ],
    GR: [
        "Acapulco de Juárez", "Ahuacuotzingo", "Ajuchitlán del Progreso", "Alcozauca de Guerrero", "Alpoyeca", "Apaxtla", "Arcelia", "Atenango del Río", "Atlamajalcingo del Monte", "Atlixtac", "Atoyac de Álvarez", "Ayutla de los Libres", "Azoyú", "Benito Juárez", "Buenavista de Cuéllar", "Coahuayutla de José María Izazaga", "Cocula", "Copala", "Copalillo", "Copanatoyac", "Coyuca de Benítez", "Coyuca de Catalán", "Cuajinicuilapa", "Cualác", "Cuautepec", "Cuetzala del Progreso", "Cutzamala de Pinzón", "Chilapa de Álvarez", "Chilpancingo de los Bravo", "Florencio Villarreal", "General Canuto A. Neri", "General Heliodoro Castillo", "Huamuxtitlán", "Huitzuco de los Figueroa", "Iguala de la Independencia", "Igualapa", "Ixcateopan de Cuauhtémoc", "Zihuatanejo de Azueta", "Juan R. Escudero", "Leonardo Bravo", "Malinaltepec", "Mártir de Cuilapan", "Metlatónoc", "Mochitlán", "Olinalá", "Ometepec", "Pedro Ascencio Alquisiras", "Petatlán", "Pilcaya", "Pungarabato", "Quechultenango", "San Luis Acatlán", "San Marcos", "San Miguel Totolapan", "Taxco de Alarcón", "Tecoanapa", "Técpan de Galeana", "Teloloapan", "Tepecoacuilco de Trujano", "Tetipac", "Tixtla de Guerrero", "Tlacoachistlahuaca", "Tlacoapa", "Tlalchapa", "Tlalixtaquilla de Maldonado", "Tlapa de Comonfort", "Tlapehuala", "La Unión de Isidoro Montes de Oca", "Xalpatláhuac", "Xochihuehuetlán", "Xochistlahuaca", "Zapotitlán Tablas", "Zirándaro", "Zitlala", "Eduardo Neri", "Acatepec", "Marquelia", "Cochoapa el Grande", "José Joaquín de Herrera", "Juchitán", "Iliatenco", "Las Vigas", "San Nicolás", "Ñuu Savi", "Santa Cruz del Rincón"
    ],
    HG: [
        "Acatlán", "Acaxochitlán", "Actopan", "Agua Blanca de Iturbide", "Ajacuba", "Alfajayucan", "Almoloya", "Apan", "El Arenal", "Atitalaquia", "Atlapexco", "Atotonilco el Grande", "Atotonilco de Tula", "Calnali", "Cardonal", "Cuautepec de Hinojosa", "Chapantongo", "Chapulhuacán", "Chilcuautla", "Eloxochitlán", "Emiliano Zapata", "Epazoyucan", "Francisco I. Madero", "Huasca de Ocampo", "Huautla", "Huazalingo", "Huehuetla", "Huejutla de Reyes", "Huichapan", "Ixmiquilpan", "Jacala de Ledezma", "Jaltocán", "Juárez Hidalgo", "Lolotla", "Metepec", "San Agustín Metzquititlán", "Metztitlán", "Mineral del Chico", "Mineral del Monte", "La Misión", "Mixquiahuala de Juárez", "Molango de Escamilla", "Nicolás Flores", "Nopala de Villagrán", "Omitlán de Juárez", "San Felipe Orizatlán", "Pacula", "Pachuca de Soto", "Pisaflores", "Progreso de Obregón", "Mineral de la Reforma", "San Agustín Tlaxiaca", "San Bartolo Tutotepec", "San Salvador", "Santiago de Anaya", "Santiago Tulantepec de Lugo Guerrero", "Singuilucan", "Tasquillo", "Tecozautla", "Tenango de Doria", "Tepeapulco", "Tepehuacán de Guerrero", "Tepeji del Río de Ocampo", "Tepetitlán", "Tetepango", "Villa de Tezontepec", "Tezontepec de Aldama", "Tianguistengo", "Tizayuca", "Tlahuelilpan", "Tlahuiltepa", "Tlanalapa", "Tlanchinol", "Tlaxcoapan", "Tolcayuca", "Tula de Allende", "Tulancingo de Bravo", "Xochiatipan", "Xochicoatlán", "Yahualica", "Zacualtipán de Ángeles", "Zapotlán de Juárez", "Zempoala", "Zimapán"
    ],
    JA: [
        "Acatic", "Acatlán de Juárez", "Ahualulco de Mercado", "Amacueca", "Amatitán", "Ameca", "San Juanito de Escobedo", "Arandas", "El Arenal", "Atemajac de Brizuela", "Atengo", "Atenguillo", "Atotonilco el Alto", "Atoyac", "Autlán de Navarro", "Ayotlán", "Ayutla", "La Barca", "Bolaños", "Cabo Corrientes", "Casimiro Castillo", "Cihuatlán", "Zapotlán el Grande", "Cocula", "Colotlán", "Concepción de Buenos Aires", "Cuautitlán de García Barragán", "Cuautla", "Cuquío", "Chapala", "Chimaltitán", "Chiquilistlán", "Degollado", "Ejutla", "Encarnación de Díaz", "Etzatlán", "El Grullo", "Guachinango", "Guadalajara", "Hostotipaquillo", "Huejúcar", "Huejuquilla el Alto", "La Huerta", "Ixtlahuacán de los Membrillos", "Ixtlahuacán del Río", "Jalostotitlán", "Jamay", "Jesús María", "Jilotlán de los Dolores", "Jocotepec", "Juanacatlán", "Juchitlán", "Lagos de Moreno", "El Limón", "Magdalena", "Santa María del Oro", "La Manzanilla de la Paz", "Mascota", "Mazamitla", "Mexticacán", "Mezquitic", "Mixtlán", "Ocotlán", "Ojuelos de Jalisco", "Pihuamo", "Poncitlán", "Puerto Vallarta", "Villa Purificación", "Quitupan", "El Salto", "San Cristóbal de la Barranca", "San Diego de Alejandría", "San Juan de los Lagos", "San Julián", "San Marcos", "San Martín de Bolaños", "San Martín Hidalgo", "San Miguel el Alto", "Gómez Farías", "San Sebastián del Oeste", "Santa María de los Ángeles", "Sayula", "Tala", "Talpa de Allende", "Tamazula de Gordiano", "Tapalpa", "Tecalitlán", "Techaluta de Montenegro", "Tecolotlán", "Tenamaxtlán", "Teocaltiche", "Teocuitatlán de Corona", "Tepatitlán de Morelos", "Tequila", "Teuchitlán", "Tizapán el Alto", "Tlajomulco de Zúñiga", "San Pedro Tlaquepaque", "Tolimán", "Tomatlán", "Tonalá", "Tonaya", "Tonila", "Totatiche", "Tototlán", "Tuxcacuesco", "Tuxcueca", "Tuxpan", "Unión de San Antonio", "Unión de Tula", "Valle de Guadalupe", "Valle de Juárez", "San Gabriel", "Villa Corona", "Villa Guerrero", "Villa Hidalgo", "Cañadas de Obregón", "Yahualica de González Gallo", "Zacoalco de Torres", "Zapopan", "Zapotiltic", "Zapotitlán de Vadillo", "Zapotlán del Rey", "Zapotlanejo", "San Ignacio Cerro Gordo"
    ],
    EM: [
        'Acambay de Ruiz Castañeda', 'Acolman', 'Aculco', 'Almoloya de Alquisiras', 'Almoloya de Juárez', 'Almoloya del Río', 'Amanalco', 'Amatepec', 'Amecameca', 'Apaxco', 'Atenco', 'Atizapán', 'Atizapán de Zaragoza', 'Atlacomulco', 'Atlautla', 'Axapusco', 'Ayapango', 'Calimaya', 'Capulhuac', 'Coacalco de Berriozábal', 'Coatepec Harinas', 'Cocotitlán', 'Coyotepec', 'Cuautitlán', 'Chalco', 'Chapa de Mota', 'Chapultepec', 'Chiautla', 'Chicoloapan', 'Chiconcuac', 'Chimalhuacán', 'Donato Guerra', 'Ecatepec de Morelos', 'Ecatzingo', 'Huehuetoca', 'Hueypoxtla', 'Huixquilucan', 'Isidro Fabela', 'Ixtapaluca', 'Ixtapan de la Sal', 'Ixtapan del Oro', 'Ixtlahuaca', 'Jaltenco', 'Jilotepec', 'Jilotzingo', 'Jiquipilco', 'Jocotitlán', 'Joquicingo', 'Juchitepec', 'Lerma', 'Malinalco', 'Melchor Ocampo', 'Metepec', 'Mexicaltzingo', 'Morelos', 'Naucalpan de Juárez', 'Nextlalpan', 'Nezahualcóyotl', 'Nicolás Romero', 'Nopaltepec', 'Ocoyoacac', 'Ocuilan', 'El Oro', 'Otumba', 'Otzoloapan', 'Otzolotepec', 'Ozumba', 'Papalotla', 'La Paz', 'Polotitlán', 'Rayón', 'San Antonio la Isla', 'San Felipe del Progreso', 'San Martín de las Pirámides', 'San Mateo Atenco', 'San Simón de Guerrero', 'Santo Tomás', 'Soyaniquilpan de Juárez', 'Sultepec', 'Tecámac', 'Tejupilco', 'Temamatla', 'Temascalapa', 'Temascalcingo', 'Temascaltepec', 'Temoaya', 'Tenancingo', 'Tenango del Aire', 'Tenango del Valle', 'Teoloyucan', 'Teotihuacán', 'Tepetlaoxtoc', 'Tepetlixpa', 'Tepotzotlán', 'Tequixquiac', 'Texcaltitlán', 'Texcalyacac', 'Texcoco', 'Tezoyuca', 'Tianguistenco', 'Timilpan', 'Tlalmanalco', 'Tlalnepantla de Baz', 'Tlatlaya', 'Toluca', 'Tonatico', 'Tultepec', 'Tultitlán', 'Valle de Bravo', 'Villa de Allende', 'Villa del Carbón', 'Villa Guerrero', 'Villa Victoria', 'Xalatlaco', 'Xonacatlán', 'Zacazonapan', 'Zacualpan', 'Zinacantepec', 'Zumpahuacán', 'Zumpango'
    ],
    MI: [
        'Acuitzio', 'Aguililla', 'Álvaro Obregón', 'Angamacutiro', 'Angangueo', 'Apatzingán', 'Aporo', 'Aquila', 'Ario', 'Arteaga', 'Briseñas', 'Buenavista', 'Carácuaro', 'Coahuayana', 'Coalcomán de Vázquez Pallares', 'Coeneo', 'Contepec', 'Copándaro', 'Cotija', 'Cuitzeo', 'Charapan', 'Charo', 'Chavinda', 'Cherán', 'Chilchota', 'Chinicuila', 'Chucándiro', 'Churintzio', 'Churumuco', 'Epitacio Huerta', 'Erongarícuaro', 'Gabriel Zamora', 'Hidalgo', 'La Huacana', 'Huandacareo', 'Huaniqueo', 'Huetamo', 'Huiramba', 'Indaparapeo', 'Irimbo', 'Ixtlán', 'Jacona', 'Jiménez', 'Jiquilpan', 'Juárez', 'Jungapeo', 'Lagunillas', 'Lázaro Cárdenas', 'Los Reyes', 'Madero', 'Maravatío', 'Marcos Castellanos', 'Morelia', 'Morelos', 'Múgica', 'Nahuatzen', 'Nocupétaro', 'Nuevo Parangaricutiro', 'Nuevo Urecho', 'Numarán', 'Ocampo', 'Pajacuarán', 'Panindícuaro', 'Parácuaro', 'Paracho', 'Pátzcuaro', 'Penjamillo', 'Peribán', 'Purépero', 'Puruándiro', 'Queréndaro', 'Quiroga', 'Sahuayo', 'San Lucas', 'Salvador Escalante', 'Senguio', 'Susupuato', 'Tacámbaro', 'Tancítaro', 'Tangamandapio', 'Tangancícuaro', 'Tanhuato', 'Taretan', 'Tingambato', 'Tinguindín', 'Tiquicheo de Nicolás Romero', 'Tlalpujahua', 'Tlazazalca', 'Tocumbo', 'Tzintzuntzan', 'Tzitzio', 'Uruapan', 'Venustiano Carranza', 'Villamar', 'Vista Hermosa', 'Yurécuaro', 'Zacapu', 'Zamora', 'Zináparo', 'Ziracuaretiro', 'Zitácuaro'
    ],
    MO: [
        'Amacuzac', 'Atlatlahucan', 'Axochiapan', 'Ayala', 'Coatlán del Río', 'Cuautla', 'Cuernavaca', 'Emiliano Zapata', 'Huitzilac', 'Jantetelco', 'Jiutepec', 'Jojutla', 'Jonacatepec', 'Mazatepec', 'Miacatlán', 'Ocuituco', 'Puente de Ixtla', 'Temixco', 'Tepalcingo', 'Tepoztlán', 'Tetecala', 'Tetela del Volcán', 'Tlalnepantla', 'Tlaltizapán de Zapata', 'Tlaquiltenango', 'Tlayacapan', 'Totolapan', 'Xochitepec', 'Yautepec', 'Yecapixtla', 'Zacatepec', 'Zacualpan de Amilpas'
    ],
    NA: [
        'Acaponeta', 'Ahuacatlán', 'Amatlán de Cañas', 'Compostela', 'Huajicori', 'Ixtlán del Río', 'Jala', 'Xalisco', 'El Nayar', 'Rosamorada', 'Ruiz', 'San Blas', 'San Pedro Lagunillas', 'Santa María del Oro', 'Santiago Ixcuintla', 'Tecuala', 'Tepic', 'Tuxpan', 'La Yesca'
    ],
    NL: [
        'Abasolo', 'Agualeguas', 'Allende', 'Anáhuac', 'Apodaca', 'Aramberri', 'Bustamante', 'Cadereyta Jiménez', 'El Carmen', 'Cerralvo', 'China', 'Ciénega de Flores', 'Doctor Arroyo', 'Doctor Coss', 'Doctor González', 'Galeana', 'García', 'General Bravo', 'General Escobedo', 'General Terán', 'General Treviño', 'General Zaragoza', 'General Zuazua', 'Guadalupe', 'Los Herreras', 'Higueras', 'Hualahuises', 'Iturbide', 'Juárez', 'Lampazos de Naranjo', 'Linares', 'Marín', 'Melchor Ocampo', 'Mier y Noriega', 'Mina', 'Montemorelos', 'Monterrey', 'Parás', 'Pesquería', 'Los Ramones', 'Rayones', 'Sabinas Hidalgo', 'Salinas Victoria', 'San Nicolás de los Garza', 'San Pedro Garza García', 'Santa Catarina', 'Santiago', 'Vallecillo', 'Villaldama'
    ],
    OA: [
        'Abejones', 'Acatlán de Pérez Figueroa', 'Asunción Cacalotepec', 'Asunción Cuyotepeji', 'Asunción Ixtaltepec', 'Asunción Nochixtlán', 'Asunción Ocotlán', 'Asunción Tlacolulita', 'Ayotzintepec', 'Cuilápam de Guerrero', 'Miahuatlán de Porfirio Díaz', 'Matías Romero Avendaño', 'Oaxaca de Juárez', 'Pochutla', 'Puerto Escondido', 'Salina Cruz', 'San Pedro Mixtepec', 'Santa Lucía del Camino', 'Santa María Huatulco', 'Tehuantepec', 'Tlaxiaco', 'Tuxtepec'
    ],
    PU: [
        "Acajete", "Acateno", "Acatlán", "Acatzingo", "Acteopan", "Ahuacatlán", "Ahuatlán", "Ahuazotepec", "Ahuehuetitla", "Ajalpan", "Albino Zertuche", "Aljojuca", "Altepexi", "Amixtlán", "Amozoc", "Aquixtla", "Atempan", "Atexcal", "Atlixco", "Atoyatempan", "Atzala", "Atzitzihuacán", "Atzitzintla", "Axutla", "Ayotoxco de Guerrero", "Calpan", "Caltepec", "Camocuautla", "Caxhuacán", "Coatepec", "Coatzingo",
        "Cohetzala",
        "Cohuecan",
        "Coronango",
        "Coxcatlán",
        "Coyomeapan",
        "Coyotepec",
        "Cuapiaxtla de Madero",
        "Cuautempan",
        "Cuautinchán",
        "Cuautlancingo",
        "Cuayuca de Andrade",
        "Cuetzalan del Progreso",
        "Cuyoaco",
        "Chalchicomula de Sesma",
        "Chapulco",
        "Chiautla",
        "Chiautzingo",
        "Chiconcuautla",
        "Chichiquila",
        "Chietla",
        "Chigmecatitlán",
        "Chignahuapan",
        "Chignautla",
        "Chila",
        "Chila de la Sal",
        "Honey",
        "Chilchotla",
        "Chinantla",
        "Domingo Arenas",
        "Eloxochitlán",
        "Epatlán",
        "Esperanza",
        "Francisco Z. Mena",
        "General Felipe Ángeles",
        "Guadalupe",
        "Guadalupe Victoria",
        "Hermenegildo Galeana",
        "Huaquechula",
        "Huatlatlauca",
        "Huauchinango",
        "Huehuetla",
        "Huehuetlán el Chico",
        "Huejotzingo",
        "Hueyapan",
        "Hueytamalco",
        "Hueytlalpan",
        "Huitzilan de Serdán",
        "Huitziltepec",
        "Atlequizayan",
        "Ixcamilpa de Guerrero",
        "Ixcaquixtla",
        "Ixtacamaxtitlán",
        "Ixtepec",
        "Izúcar de Matamoros",
        "Jalpan",
        "Jolalpan",
        "Jonotla",
        "Jopala",
        "Juan C. Bonilla",
        "Juan Galindo",
        "Juan N. Méndez",
        "Lafragua",
        "Libres",
        "La Magdalena Tlatlauquitepec",
        "Mazapiltepec de Juárez",
        "Mixtla",
        "Molcaxac",
        "Cañada Morelos",
        "Naupan",
        "Nauzontla",
        "Nealtican",
        "Nicolás Bravo",
        "Nopalucan",
        "Ocotepec",
        "Ocoyucan",
        "Olintla",
        "Oriental",
        "Pahuatlán",
        "Palmar de Bravo",
        "Pantepec",
        "Petlalcingo",
        "Piaxtla",
        "Puebla",
        "Quecholac",
        "Quimixtlán",
        "Rafael Lara Grajales",
        "Los Reyes de Juárez",
        "San Andrés Cholula",
        "San Antonio Cañada",
        "San Diego La Mesa Tochimiltzingo",
        "San Felipe Teotlalcingo",
        "San Felipe Tepatlán",
        "San Gabriel Chilac",
        "San Gregorio Atzompa",
        "San Jerónimo Tecuanipan",
        "San Jerónimo Xayacatlán",
        "San José Chiapa",
        "San José Miahuatlán",
        "San Juan Atenco",
        "San Juan Atzompa",
        "San Martín Texmelucan",
        "San Martín Totoltepec",
        "San Matías Tlalancaleca",
        "San Miguel Ixitlán",
        "San Miguel Xoxtla",
        "San Nicolás Buenos Aires",
        "San Nicolás de los Ranchos",
        "San Pablo Anicano",
        "San Pedro Cholula",
        "San Pedro Yeloixtlahuaca",
        "San Salvador el Seco",
        "San Salvador el Verde",
        "San Salvador Huixcolotla",
        "San Sebastián Tlacotepec",
        "Santa Catarina Tlaltempan",
        "Santa Inés Ahuatempan",
        "Santa Isabel Cholula",
        "Santiago Miahuatlán",
        "Huehuetlán el Grande",
        "Santo Tomás Hueyotlipan",
        "Soltepec",
        "Tecali de Herrera",
        "Tecamachalco",
        "Tecomatlán",
        "Tehuacán",
        "Tehuitzingo",
        "Tenampulco",
        "Teopantlán",
        "Teotlalco",
        "Tepanco de López",
        "Tepango de Rodríguez",
        "Tepatlaxco de Hidalgo",
        "Tepeaca",
        "Tepemaxalco",
        "Tepeojuma",
        "Tepetzintla",
        "Tepexco",
        "Tepexi de Rodríguez",
        "Tepeyahualco",
        "Tepeyahualco de Cuauhtémoc",
        "Tetela de Ocampo",
        "Teteles de Ávila Castillo",
        "Teziutlán",
        "Tianguismanalco",
        "Tilapa",
        "Tlacotepec de Benito Juárez",
        "Tlacuilotepec",
        "Tlachichuca",
        "Tlahuapan",
        "Tlaltenango",
        "Tlanepantla",
        "Tlaola",
        "Tlapacoya",
        "Tlapanalá",
        "Tlatlauquitepec",
        "Tlaxco",
        "Tochimilco",
        "Tochtepec",
        "Totoltepec de Guerrero",
        "Tulcingo",
        "Tuzamapan de Galeana",
        "Tzicatlacoyan",
        "Venustiano Carranza",
        "Vicente Guerrero",
        "Xayacatlán de Bravo",
        "Xicotepec",
        "Xicotlán",
        "Xiutetelco",
        "Xochiapulco",
        "Xochiltepec",
        "Xochitlán de Vicente Suárez",
        "Xochitlán Todos Santos",
        "Yaonáhuac",
        "Yehualtepec",
        "Zacapala",
        "Zacapoaxtla",
        "Zacatlán",
        "Zapotitlán",
        "Zapotitlán de Méndez",
        "Zaragoza",
        "Zautla",
        "Zihuateutla",
        "Zinacatepec",
        "Zongozotla",
        "Zoquiapan",
        "Zoquitlán"
    ],
    QT: [
        "Amealco de Bonfil", "Pinal de Amoles", "Arroyo Seco", "Cadereyta de Montes", "Colón", "Corregidora", "Ezequiel Montes", "Huimilpan", "Jalpan de Serra", "Landa de Matamoros", "Pedro Escobedo", "Peñamiller", "Querétaro", "San Joaquín", "San Juan del Río", "Tequisquiapan", "Tolimán", "El Marqués"
    ],
    QR: [
        'Benito Juárez', 'Cozumel', 'Felipe Carrillo Puerto', 'Isla Mujeres', 'José María Morelos', 'Lázaro Cárdenas', 'Othón P. Blanco', 'Solidaridad', 'Tulum', 'Bacalar', 'Puerto Morelos'
    ],
    SL: [
        "Ahualulco",
        "Alaquines",
        "Aquismón",
        "Armadillo de los Infante",
        "Cárdenas",
        "Catorce",
        "Cedral",
        "Cerritos",
        "Cerro de San Pedro",
        "Ciudad del Maíz",
        "Ciudad Fernández",
        "Tancanhuitz",
        "Ciudad Valles",
        "Coxcatlán",
        "Charcas",
        "Ébano",
        "Guadalcázar",
        "Huehuetlán",
        "Lagunillas",
        "Matehuala",
        "Mexquitic de Carmona",
        "Moctezuma",
        "Rayón",
        "Rioverde",
        "Salinas",
        "San Antonio",
        "San Ciro de Acosta",
        "San Luis Potosí",
        "San Martín Chalchicuautla",
        "San Nicolás Tolentino",
        "Santa Catarina",
        "Santa María del Río",
        "Santo Domingo",
        "San Vicente Tancuayalab",
        "Soledad de Graciano Sánchez",
        "Tamasopo",
        "Tamazunchale",
        "Tampacán",
        "Tampamolón Corona",
        "Tamuín",
        "Tanlajás",
        "Tanquián de Escobedo",
        "Tierra Nueva",
        "Vanegas",
        "Venado",
        "Villa de Arriaga",
        "Villa de Guadalupe",
        "Villa de la Paz",
        "Villa de Ramos",
        "Villa de Reyes",
        "Villa Hidalgo",
        "Villa Juárez",
        "Axtla de Terrazas",
        "Xilitla",
        "Zaragoza",
        "Villa de Arista",
        "Matlapa",
        "El Naranjo",
        "Villa de Pozos"
    ],
    SI: [
        'Ahome', 'Angostura', 'Badiraguato', 'Choix', 'Concordia', 'Cosalá', 'Culiacán', 'El Fuerte', 'Guasave', 'Mazatlán', 'Mocorito', 'Navolato', 'Rosario', 'Salvador Alvarado', 'San Ignacio', 'Sinaloa', 'Elota', 'Escuinapa'
    ],
    SO: [
        'Aconchi', 'Agua Prieta', 'Alamos', 'Altar', 'Arizpe', 'Atil', 'Bacadéhuachi', 'Bacanora', 'Bacerac', 'Bacoachi', 'Bácum', 'Banámichi', 'Baviácora', 'Bavispe', 'Benjamín Hill', 'Caborca', 'Cajeme', 'Cananea', 'Carbó', 'La Colorada', 'Cucurpe', 'Cumpas', 'Divisaderos', 'Empalme', 'Etchojoa', 'Fronteras', 'Granados', 'Guaymas', 'Hermosillo', 'Huachinera', 'Huásabas', 'Huépac', 'Imuris', 'Magdalena', 'Mazatán', 'Moctezuma', 'Naco', 'Nácori Chico', 'Nacozari de García', 'Navojoa', 'Nogales', 'Onavas', 'Opodepe', 'Oquitoa', 'Pitiquito', 'Puerto Peñasco', 'Quiriego', 'Rayón', 'Rosario', 'Sahuaripa', 'San Felipe de Jesús', 'San Javier', 'San Luis Río Colorado', 'San Miguel de Horcasitas', 'San Pedro de la Cueva', 'Santa Ana', 'Santa Cruz', 'Sáric', 'Soyopa', 'Suaqui Grande', 'Tepache', 'Trincheras', 'Tubutama', 'Ures', 'Villa Hidalgo', 'Villa Pesqueira', 'Yécora'
    ],
    TB: [
        'Balancán', 'Cárdenas', 'Centla', 'Centro', 'Comalcalco', 'Cunduacán', 'Emiliano Zapata', 'Huimanguillo', 'Jalapa', 'Jalpa de Méndez', 'Jonuta', 'Macuspana', 'Nacajuca', 'Paraíso', 'Tacotalpa', 'Teapa', 'Tenosique'
    ],
    TM: [
        'Abasolo', 'Aldama', 'Altamira', 'Antiguo Morelos', 'Burgos', 'Bustamante', 'Camargo', 'Casas', 'Ciudad Madero', 'Cruillas', 'Gómez Farías', 'González', 'Güémez', 'Guerrero', 'Gustavo Díaz Ordaz', 'Hidalgo', 'Jaumave', 'Jiménez', 'Llera', 'Mainero', 'Mante', 'Matamoros', 'Méndez', 'Mier', 'Miguel Alemán', 'Miquihuana', 'Nuevo Laredo', 'Nuevo Morelos', 'Ocampo', 'Padilla', 'Palmillas', 'Río Bravo', 'San Carlos', 'San Fernando', 'San Nicolás', 'Soto la Marina', 'Tampico', 'Tula', 'Valle Hermoso', 'Victoria', 'Villagrán', 'Xicoténcatl'
    ],
    TL: [
        'Amaxac de Guerrero', 'Apetatitlán de Antonio Carvajal', 'Apizaco', 'Atlangatepec', 'Atltzayanca', 'Benito Juárez', 'Calpulalpan', 'Chiautempan', 'Contla de Juan Cuamatzi', 'Cuapiaxtla', 'Cuaxomulco', 'El Carmen Tequexquitla', 'Emiliano Zapata', 'Españita', 'Huamantla', 'Hueyotlipan', 'Ixtacuixtla de Mariano Matamoros', 'Ixtenco', 'La Magdalena Tlaltelulco', 'Lázaro Cárdenas', 'Mazatecochco de José María Morelos', 'Muñoz de Domingo Arenas', 'Nanacamilpa de Mariano Arista', 'Natívitas', 'Panotla', 'Papalotla de Xicohténcatl', 'San Damián Texoloc', 'San Francisco Tetlanohcan', 'San Jerónimo Zacualpan', 'San José Teacalco', 'San Juan Huactzinco', 'San Lorenzo Axocomanitla', 'San Lucas Tecopilco', 'San Luis Teolocholco', 'San Pablo del Monte', 'Sanctorum de Lázaro Cárdenas', 'Santa Ana Nopalucan', 'Santa Apolonia Teacalco', 'Santa Catarina Ayometla', 'Santa Cruz Quilehtla', 'Santa Cruz Tlaxcala', 'Santa Isabel Xiloxoxtla', 'Tenancingo', 'Teolocholco', 'Tepetitla de Lardizábal', 'Terrenate', 'Tetla de la Solidaridad', 'Tetlatlahuca', 'Tlaxcala', 'Tlaxco', 'Tzompantepec', 'Xaloztoc', 'Xaltocan', 'Yauhquemehcan', 'Zacatelco', 'Ziltlaltpec'
    ],
    VE: [
        'Acajete', 'Acayucan', 'Actopan', 'Acula', 'Acultzingo', 'Agua Dulce', 'Alvarado', 'Amatitlán', 'Amatlán de los Reyes', 'Angel R. Cabada', 'La Antigua', 'Apazapan', 'Aquila', 'Astacinga', 'Atlahuilco', 'Atoyac', 'Atzacan', 'Atzalan', 'Benito Juárez', 'Boca del Río', 'Calcahualco', 'Camerino Z. Mendoza', 'Catemaco', 'Cazones de Herrera', 'Cerro Azul', 'Citlaltépetl', 'Coacoatzintla', 'Coahuitlán', 'Coatepec', 'Coatzacoalcos', 'Coatzintla', 'Coetzala', 'Colipa', 'Comapa', 'Córdoba', 'Cosamaloapan de Carpio', 'Cosautlán de Carregal', 'Coscomatepec', 'Cosoleacaque', 'Cotaxtla', 'Coxquihui', 'Coyutla', 'Cuichapa', 'Cuitláhuac', 'Chacaltianguis', 'Chalma', 'Chiconamel', 'Chiconquiaco', 'Chicontepec', 'Chinameca', 'Chinampa de Gorostiza', 'Chocamán', 'Chontla', 'Chumatlán', 'Ébano', 'Emiliano Zapata', 'Espinal', 'Filomeno Mata', 'Fortín', 'Gutiérrez Zamora', 'Hidalgo', 'Huatusco', 'Huayacocotla', 'Hueyapan de Ocampo', 'Ignacio de la Llave', 'Ilhuilco', 'Ixcatepec', 'Ixhuatlán del Café', 'Ixhuatlán del Sureste', 'Ixhuatlán de Madero', 'Ixhuacán de los Reyes', 'Ixtaczoquitlán', 'Jalacingo', 'Jalcomulco', 'Jamapa', 'Jesús Carranza', 'Jilotepec', 'Juan Rodríguez Clara', 'Juchique de Ferrer', 'Landero y Coss', 'Las Choapas', 'Las Minas', 'León', 'Lerdo de Tejada', 'Los Reyes', 'Magdalena', 'Maltrata', 'Manlio Fabio Altamirano', 'Mariano Escobedo', 'Martínez de la Torre', 'Mecatlán', 'Mecayucan', 'Medellín', 'Minatitlán', 'Misantla', 'Mixtla de Altamirano', 'Moloacán', 'Naranjal', 'Nautla', 'Nogales', 'Orizaba', 'Otatitlán', 'Oteapan', 'Ozuluama de Mascareñas', 'Pajapan', 'Pánuco', 'Papantla', 'Paso de Ovejas', 'Paso del Macho', 'Perote', 'Platón Sánchez', 'Playa Vicente', 'Poza Rica de Hidalgo', 'Pueblo Viejo', 'Puente Nacional', 'Rafael Delgado', 'Rafael Lucio', 'Río Blanco', 'Saltabarranca', 'San Andrés Tuxtla', 'San Juan Evangelista', 'San Rafael', 'Santiago Tuxtla', 'Sayula de Alemán', 'Sochiapa', 'Soledad de Doblado', 'Soteapan', 'Tamalín', 'Tamiahua', 'Tampico Alto', 'Tantima', 'Tantoyuca', 'Tatahuicapan de Juárez', 'Tatatila', 'Tempoal', 'Tenampa', 'Tenochtitlán', 'Teocelo', 'Tepetlán', 'Tepetzintla', 'Tequila', 'Texhuacán', 'Texistepec', 'Tezonapa', 'Tierra Blanca', 'Tihuatlán', 'Tlacojalpan', 'Tlacolulan', 'Tlacotalpan', 'Tlacotepec de Mejía', 'Tlachichilco', 'Tlalnelhuayocan', 'Tlapacoyan', 'Tlalixcoyan', 'Tlaquilpa', 'Tonayán', 'Tres Valles', 'Tuxpan', 'Tuxtilla', 'Ursulo Galván', 'Vega de Alatorre', 'Veracruz', 'Villa Aldama', 'Xalapa', 'Xico', 'Zacualpan', 'Zaragoza', 'Zongolica', 'Zontecomatlán de López y Fuentes'
    ],
    YU: [
        'Abalá', 'Acanceh', 'Akil', 'Baca', 'Bokobá', 'Buctzotz', 'Cacalchén', 'Calotmul', 'Cansahcab', 'Cantamayec', 'Celestún', 'Cenotillo', 'Conkal', 'Cuncunul', 'Cuzamá', 'Chacsinkín', 'Chankom', 'Chapab', 'Chemax', 'Chichimilá', 'Chicxulub Pueblo', 'Chikindzonot', 'Chocholá', 'Chumayel', 'Dzán', 'Dzemul', 'Dzidzantún', 'Dzilam de Bravo', 'Dzilam González', 'Dzitás', 'Dzoncauich', 'Espita', 'Halachó', 'Hocabá', 'Hoctún', 'Homún', 'Huhí', 'Hunucmá', 'Izamal', 'Ixil', 'Kanasín', 'Kantunil', 'Kaua', 'Kinchil', 'Kopomá', 'Mama', 'Maní', 'Maxcanú', 'Mayapán', 'Mérida', 'Mocochá', 'Motul', 'Muna', 'Muxupip', 'Opichén', 'Oxkutzcab', 'Panabá', 'Peto', 'Progreso', 'Quintana Roo', 'Río Lagartos', 'Sacalum', 'Samahil', 'Sanahcat', 'San Felipe', 'Santa Elena', 'Seyé', 'Sinanché', 'Sotuta', 'Sucilá', 'Sudzal', 'Sumá', 'Tahdziú', 'Tahmek', 'Teabo', 'Tecoh', 'Tekal de Venegas', 'Tekantó', 'Tekax', 'Tekit', 'Tekom', 'Telchac Pueblo', 'Telchac Puerto', 'Temax', 'Temozón', 'Tepakán', 'Tetiz', 'Teya', 'Ticul', 'Timucuy', 'Tinum', 'Tixcacalcupul', 'Tixkokob', 'Tixmehuac', 'Tixpéhual', 'Tizimín', 'Tunkás', 'Tzucacab', 'Uayma', 'Umán', 'Valladolid', 'Xocchel', 'Yaxcabá', 'Yaxkukul', 'Yobaín'
    ],
    ZA: [
        'Apozol', 'Calera', 'Cañitas de Felipe Pescador', 'Concepción del Oro', 'Cuauhtémoc', 'Chalchihuites', 'Fresnillo', 'Genaro Codina', 'General Francisco R. Murguía', 'General Pánfilo Natera', 'Guadalupe', 'Huanusco', 'Jalpa', 'Jerez', 'Jiménez del Teul', 'Juan Aldama', 'Juchipila', 'Loreto', 'Luis Moya', 'Mazapil', 'Melchor Ocampo', 'Mezquital del Oro', 'Miguel Auza', 'Momax', 'Monte Escobedo', 'Morelos', 'Moyahua de Estrada', 'Nochistlán de Mejía', 'Noria de Ángeles', 'Ojocaliente', 'Pánuco', 'Pinos', 'Río Grande', 'Sain Alto', 'El Salvador', 'Sombrerete', 'Susticacán', 'Tabasco', 'Tepechitlán', 'Tepetongo', 'Teúl de González Ortega', 'Tlaltenango de Sánchez Román', 'Valparaíso', 'Vetagrande', 'Villa de Cos', 'Villa García', 'Villa González Ortega', 'Villa Hidalgo', 'Villanueva', 'Zacatecas'
    ],
};

export default municipiosPorEstado;