version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:21.0  # Usa OpenJDK 21 con Gradle
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Verificar Gradle
          command: gradle --version
      - run:
          name: Permiso de ejecucion de ./gradlew
          command: chmod +x ./gradlew
      - run:
          name: Compilar la aplicación con Gradle
          command: ./gradlew build -x test
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar
  docker_build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Iniciar sesion en Docker Hub
          command: echo $DOCKERHUB_TOKEN | docker login -u rego199903 --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t rego199903/smarshop:latest .
      - run:
          name: Verificar imágenes locales
          command: docker images
      - run:
          name: Subir imagen a Docker Hub
          command: |
            docker push rego199903/smartshop:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
