version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:21.0  # Usa OpenJDK 21 con Gradle

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Verificar Gradle
          command: gradle --version
      - run:
          name: Permiso de ejecucion de ./gradlew
          command: chmod +x ./gradlew
      - run:
          name: Compilar la aplicación con Gradle
          command: ./gradlew build -x test
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar

  docker_build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Construir la imagen Docker
          command: |
            docker build -t $DOCKERHUB_USERNAME/smartshop:latest .
      - run:
          name: Iniciar sesión en Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Etiquetar la imagen
          command: |
            TAG=$(git rev-parse --short HEAD)
            docker tag $DOCKERHUB_USERNAME/smartshop:latest $DOCKERHUB_USERNAME/smartshop:$TAG
      - run:
          name: Subir imagen a Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/smartshop:latest
            docker push $DOCKERHUB_USERNAME/smartshop:$TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
